import { Database } from '@/types/database'

type Product = Database['public']['Tables']['products']['Row'] & {
    category: Database['public']['Tables']['categories']['Row']
    specs: Database['public']['Tables']['specs']['Row'][]
}

export const MOCK_CATEGORIES = [
    {
        id: 'c1',
        name: 'Headphones',
        slug: 'headphones',
        created_at: new Date().toISOString(),
    },
    {
        id: 'c2',
        name: 'Gaming Gear',
        slug: 'gaming-gear',
        created_at: new Date().toISOString(),
    },
]

export const MOCK_PRODUCTS: any[] = [
    // Headphones
    {
        id: 'p1',
        category_id: 'c1',
        name: 'Sony WH-1000XM5',
        slug: 'sony-wh-1000xm5',
        price_min: 348,
        price_max: 399,
        overall_score: 9.2,
        sound_score: 9.0,
        fps_score: 7.5,
        comfort_score: 9.5,
        build_score: 8.8,
        pros: ['Industry-leading ANC', 'Lightweight comfort', 'Great battery life'],
        cons: ['Non-folding design', 'Pricey'],
        affiliate_url: 'https://amazon.com/dp/example1',
        image_url: '/images/sony-xm5.jpg',
        created_at: new Date().toISOString(),
        category: MOCK_CATEGORIES[0],
        specs: [
            { id: 's1', product_id: 'p1', key: 'Type', value: 'Over-ear', created_at: new Date().toISOString() },
            { id: 's2', product_id: 'p1', key: 'Battery', value: '30 hours', created_at: new Date().toISOString() },
        ],
    },
    {
        id: 'p2',
        category_id: 'c1',
        name: 'Bose QuietComfort 45',
        slug: 'bose-qc45',
        price_min: 279,
        price_max: 329,
        overall_score: 8.8,
        sound_score: 8.5,
        fps_score: 7.0,
        comfort_score: 9.8,
        build_score: 8.5,
        pros: ['Supreme comfort', 'Excellent ANC', 'Physical buttons'],
        cons: ['Sound is just okay', 'Dated design'],
        affiliate_url: 'https://amazon.com/dp/example2',
        image_url: '/images/bose-qc45.jpg',
        created_at: new Date().toISOString(),
        category: MOCK_CATEGORIES[0],
        specs: [
            { id: 's3', product_id: 'p2', key: 'Type', value: 'Over-ear', created_at: new Date().toISOString() },
            { id: 's4', product_id: 'p2', key: 'Battery', value: '24 hours', created_at: new Date().toISOString() },
        ],
    },
    {
        id: 'p3',
        category_id: 'c1',
        name: 'Sennheiser Momentum 4',
        slug: 'sennheiser-momentum-4',
        price_min: 299,
        price_max: 349,
        overall_score: 9.1,
        sound_score: 9.4,
        fps_score: 8.0,
        comfort_score: 9.0,
        build_score: 8.9,
        pros: ['Incredible 60hr battery', 'Audiophile sound', 'Modern look'],
        cons: ['ANC weaker than Sony', 'Touch controls finicky'],
        affiliate_url: 'https://amazon.com/dp/example3',
        image_url: '/images/sennheiser-m4.jpg',
        created_at: new Date().toISOString(),
        category: MOCK_CATEGORIES[0],
        specs: [
            { id: 's5', product_id: 'p3', key: 'Type', value: 'Over-ear', created_at: new Date().toISOString() },
            { id: 's6', product_id: 'p3', key: 'Battery', value: '60 hours', created_at: new Date().toISOString() },
        ],
    },
    // Gaming Gear (Mice)
    {
        id: 'p4',
        category_id: 'c2',
        name: 'Logitech G Pro X Superlight',
        slug: 'logitech-g-pro-x-superlight',
        price_min: 129,
        price_max: 159,
        overall_score: 9.5,
        sound_score: null,
        fps_score: 9.8,
        comfort_score: 9.5,
        build_score: 9.0,
        pros: ['Extremely light (<63g)', 'Flawless sensor', 'Safe shape for all'],
        cons: ['No USB-C (Micro-USB)', 'Expensive'],
        affiliate_url: 'https://amazon.com/dp/example4',
        image_url: '/images/gpro-x.jpg',
        created_at: new Date().toISOString(),
        category: MOCK_CATEGORIES[1],
        specs: [
            { id: 's7', product_id: 'p4', key: 'Weight', value: '<63g', created_at: new Date().toISOString() },
            { id: 's8', product_id: 'p4', key: 'Sensor', value: 'HERO 25K', created_at: new Date().toISOString() },
        ],
    },
    {
        id: 'p5',
        category_id: 'c2',
        name: 'Razer DeathAdder V3 Pro',
        slug: 'razer-deathadder-v3-pro',
        price_min: 149,
        price_max: 149,
        overall_score: 9.4,
        sound_score: null,
        fps_score: 9.7,
        comfort_score: 9.3,
        build_score: 9.2,
        pros: ['Best ergo shape', '4KHz polling ready', 'Optical switches'],
        cons: ['Pricey', 'Large for small hands'],
        affiliate_url: 'https://amazon.com/dp/example5',
        image_url: '/images/dav3.jpg',
        created_at: new Date().toISOString(),
        category: MOCK_CATEGORIES[1],
        specs: [
            { id: 's9', product_id: 'p5', key: 'Weight', value: '63g', created_at: new Date().toISOString() },
            { id: 's10', product_id: 'p5', key: 'Sensor', value: 'Focus Pro 30K', created_at: new Date().toISOString() },
        ],
    },
    {
        id: 'p6',
        category_id: 'c2',
        name: 'Wooting 60HE',
        slug: 'wooting-60he',
        price_min: 175,
        price_max: 175,
        overall_score: 9.7,
        sound_score: null,
        fps_score: 10.0,
        comfort_score: 8.5,
        build_score: 9.0,
        pros: ['Rapid Trigger is cheating', 'Analog input', 'Great software'],
        cons: ['Plastic case', 'Long shipping times'],
        affiliate_url: 'https://wooting.io/example',
        image_url: '/images/wooting60he.jpg',
        created_at: new Date().toISOString(),
        category: MOCK_CATEGORIES[1],
        specs: [
            { id: 's11', product_id: 'p6', key: 'Switch', value: 'Lekker Hall Effect', created_at: new Date().toISOString() },
            { id: 's12', product_id: 'p6', key: 'Size', value: '60%', created_at: new Date().toISOString() },
        ],
    },
]
