const { createClient } = require('@supabase/supabase-js');
require('dotenv').config({ path: '.env.local' });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
);

// ข้อมูลสเปคของทุกสินค้า — จับคู่ด้วย slug
const specsDB = {

  // ════════════════════════════════════════
  // SONY HEADPHONES
  // ════════════════════════════════════════
  "sony-wh-1000xm5": [
    { key: "ประเภทหูฟัง", value: "Over-Ear (Closed-Back)" },
    { key: "ไดรเวอร์", value: "30mm Dynamic, Dome type" },
    { key: "ตอบสนองความถี่", value: "4Hz – 40,000Hz (Hi-Res Audio)" },
    { key: "ระบบตัดเสียง", value: "AI-powered ANC — Dual chip (QN1 + V1)" },
    { key: "Bluetooth", value: "5.2 / รองรับ LDAC, AAC, SBC" },
    { key: "แบตเตอรี่", value: "30 ชม. (ANC ON) / 40 ชม. (ANC OFF)" },
    { key: "ชาร์จเร็ว", value: "3 นาที = 3 ชั่วโมงฟัง" },
    { key: "ไมค์", value: "8 ไมโครโฟน (4 ไมค์ในแต่ละข้าง)" },
    { key: "น้ำหนัก", value: "250 กรัม" },
    { key: "การเชื่อมต่อ", value: "Multipoint (2 อุปกรณ์พร้อมกัน)" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
  ],
  "sony-wh-ult900n": [
    { key: "ประเภทหูฟัง", value: "Over-Ear (Closed-Back)" },
    { key: "ไดรเวอร์", value: "40mm Dynamic" },
    { key: "ตอบสนองความถี่", value: "20Hz – 20,000Hz" },
    { key: "ระบบตัดเสียง", value: "Noise Cancelling — Chip V1" },
    { key: "โหมดพิเศษ", value: "ULT1 (เบสนุ่ม) / ULT2 (เบสสุด)" },
    { key: "Bluetooth", value: "5.2 / รองรับ LDAC, AAC, SBC" },
    { key: "แบตเตอรี่", value: "38 ชม. (ANC ON) / 50 ชม. (ANC OFF)" },
    { key: "การเชื่อมต่อ", value: "Multipoint (2 อุปกรณ์)" },
    { key: "น้ำหนัก", value: "255 กรัม" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
  ],
  "sony-wh-ch720n": [
    { key: "ประเภทหูฟัง", value: "Over-Ear (Closed-Back)" },
    { key: "ไดรเวอร์", value: "30mm Dynamic" },
    { key: "ระบบตัดเสียง", value: "ANC — Chip QN1" },
    { key: "Bluetooth", value: "5.2 / รองรับ AAC, SBC" },
    { key: "แบตเตอรี่", value: "35 ชม. (ANC ON) / 50 ชม. (ANC OFF)" },
    { key: "น้ำหนัก", value: "192 กรัม (เบาที่สุดในซีรีส์ CH)" },
    { key: "การเชื่อมต่อ", value: "Multipoint (2 อุปกรณ์)" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
    { key: "ไมค์", value: "2 ไมโครโฟน Beam-forming" },
  ],
  "sony-wh-1000xm6": [
    { key: "ประเภทหูฟัง", value: "Over-Ear (Closed-Back)" },
    { key: "ไดรเวอร์", value: "30mm Dynamic (Upgraded Gen 2)" },
    { key: "ตอบสนองความถี่", value: "4Hz – 40,000Hz (Hi-Res Audio)" },
    { key: "ระบบตัดเสียง", value: "AI Noise Cancelling — Chip QN3" },
    { key: "Bluetooth", value: "5.3 / รองรับ LDAC, AAC, SBC, Auracast" },
    { key: "แบตเตอรี่", value: "30 ชม. (ANC ON)" },
    { key: "ชาร์จเร็ว", value: "3 นาที = 3 ชั่วโมงฟัง" },
    { key: "ไมค์", value: "8 ไมโครโฟน AI Beamforming" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
    { key: "น้ำหนัก", value: "~250 กรัม" },
  ],
  "sony-wh-ch520": [
    { key: "ประเภทหูฟัง", value: "On-Ear" },
    { key: "ไดรเวอร์", value: "30mm Dynamic" },
    { key: "Bluetooth", value: "5.2 / รองรับ AAC, SBC" },
    { key: "แบตเตอรี่", value: "50 ชั่วโมง (สถิติในซีรีส์)" },
    { key: "ชาร์จเร็ว", value: "10 นาที = 1.5 ชั่วโมงฟัง" },
    { key: "น้ำหนัก", value: "147 กรัม" },
    { key: "ฟีเจอร์พิเศษ", value: "DSEE (คืนคุณภาพเสียงไฟล์บีบอัด)" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
  ],
  "sony-mdr-zx310ap": [
    { key: "ประเภทหูฟัง", value: "On-Ear มีสาย" },
    { key: "ไดรเวอร์", value: "30mm Ferrite" },
    { key: "ตอบสนองความถี่", value: "10Hz – 22,000Hz" },
    { key: "อิมพีแดนซ์", value: "24 โอห์ม" },
    { key: "ความไวเสียง", value: "98 dB/mW" },
    { key: "สายเคเบิล", value: "Y-type 1.2 เมตร" },
    { key: "ไมค์", value: "มีไมค์พร้อมปุ่มรับสาย" },
    { key: "น้ำหนัก", value: "120 กรัม" },
    { key: "แจ็ค", value: "3.5mm Stereo" },
  ],
  "sony-inzone-h9": [
    { key: "ประเภทหูฟัง", value: "Over-Ear Wireless Gaming" },
    { key: "ไดรเวอร์", value: "40mm Dynamic" },
    { key: "ระบบตัดเสียง", value: "ANC (Noise Cancelling)" },
    { key: "ระบบเสียง", value: "360 Spatial Sound for Gaming" },
    { key: "Bluetooth", value: "5.0" },
    { key: "ช่องสัญญาณไร้สาย", value: "2.4GHz USB Dongle + Bluetooth" },
    { key: "แบตเตอรี่", value: "32 ชม. (ANC ON) / 40 ชม. (ANC OFF)" },
    { key: "ความหน่วงเสียง", value: "ต่ำมากผ่าน 2.4GHz Dongle" },
    { key: "ไมค์", value: "Unidirectional + Bidirectional" },
    { key: "น้ำหนัก", value: "297 กรัม" },
    { key: "พอร์ตชาร์จ", value: "USB-C (Play while charging)" },
    { key: "Platform", value: "PC, PS5, Mobile" },
  ],
  "sony-inzone-h7": [
    { key: "ประเภทหูฟัง", value: "Over-Ear Wireless Gaming" },
    { key: "ไดรเวอร์", value: "40mm Dynamic" },
    { key: "ระบบเสียง", value: "360 Spatial Sound for Gaming" },
    { key: "ช่องสัญญาณไร้สาย", value: "2.4GHz USB Dongle + Bluetooth 5.0" },
    { key: "แบตเตอรี่", value: "40 ชม." },
    { key: "ไมค์", value: "Retractable Boom Mic" },
    { key: "น้ำหนัก", value: "264 กรัม" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
    { key: "Platform", value: "PC, PS5, Mobile" },
  ],
  "sony-wi-oe610-float-run": [
    { key: "ประเภทหูฟัง", value: "Open-Ear Sport (ลอยหน้าหู)" },
    { key: "ไดรเวอร์", value: "17mm Dynamic" },
    { key: "Bluetooth", value: "5.0 / SBC, AAC" },
    { key: "แบตเตอรี่", value: "10 ชั่วโมง" },
    { key: "กันน้ำ", value: "IPX4" },
    { key: "น้ำหนัก", value: "33 กรัม" },
    { key: "การออกแบบ", value: "Float Design ลอยหน้าหูชั้นใน" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
  ],

  // Sony Earbuds
  "sony-mdr-e9lp": [
    { key: "ประเภทหูฟัง", value: "Earbud มีสาย" },
    { key: "ไดรเวอร์", value: "13.5mm Neodymium" },
    { key: "ตอบสนองความถี่", value: "20Hz – 20,000Hz" },
    { key: "ความไวเสียง", value: "105 dB/mW" },
    { key: "อิมพีแดนซ์", value: "16 โอห์ม" },
    { key: "สายเคเบิล", value: "1.2 เมตร" },
    { key: "แจ็ค", value: "3.5mm Stereo" },
    { key: "น้ำหนัก", value: "ประมาณ 3 กรัม" },
  ],
  "sony-wi-c100": [
    { key: "ประเภทหูฟัง", value: "In-Ear Neckband Wireless" },
    { key: "ไดรเวอร์", value: "9mm" },
    { key: "Bluetooth", value: "5.0 / SBC, AAC" },
    { key: "แบตเตอรี่", value: "25 ชั่วโมง" },
    { key: "กันน้ำ", value: "IPX4" },
    { key: "น้ำหนัก", value: "13 กรัม" },
    { key: "ไมค์", value: "มีไมค์ + ปุ่มรับสาย" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
    { key: "สายคล้อง", value: "แม่เหล็กดูดสองข้างได้" },
  ],
  "sony-ier-ex15c": [
    { key: "ประเภทหูฟัง", value: "In-Ear มีสาย (Type-C)" },
    { key: "ไดรเวอร์", value: "9mm Neodymium" },
    { key: "ตอบสนองความถี่", value: "5Hz – 40,000Hz (Hi-Res Audio)" },
    { key: "ความไวเสียง", value: "107 dB" },
    { key: "แจ็ค", value: "USB Type-C" },
    { key: "สายเคเบิล", value: "1.2 เมตร, Y-type" },
    { key: "ไมค์", value: "มีไมค์ + ปุ่มรับสาย" },
    { key: "น้ำหนัก", value: "3 กรัม" },
  ],
  "sony-wf-c710n": [
    { key: "ประเภทหูฟัง", value: "True Wireless (TWS)" },
    { key: "ไดรเวอร์", value: "5mm Dynamic" },
    { key: "ระบบตัดเสียง", value: "ANC + Ambient Sound" },
    { key: "Bluetooth", value: "5.3 / SBC, AAC" },
    { key: "แบตเตอรี่", value: "7.5 ชม. + 22.5 ชม. (กล่อง) รวม 30 ชม." },
    { key: "กันน้ำ", value: "IPX4" },
    { key: "น้ำหนัก", value: "4.8 กรัม ต่อข้าง" },
    { key: "ชาร์จเร็ว", value: "10 นาที = 60 นาทีฟัง" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
    { key: "จับคู่", value: "Google Fast Pair / Swift Pair" },
  ],
  "sony-wf-c510": [
    { key: "ประเภทหูฟัง", value: "True Wireless (TWS)" },
    { key: "ไดรเวอร์", value: "5.8mm Dynamic" },
    { key: "Bluetooth", value: "5.3 / SBC, AAC" },
    { key: "แบตเตอรี่", value: "11 ชม. + 22 ชม. (กล่อง) รวม 33 ชม." },
    { key: "กันน้ำ", value: "IPX4" },
    { key: "น้ำหนัก", value: "5.4 กรัม ต่อข้าง" },
    { key: "ชาร์จเร็ว", value: "10 นาที = 60 นาทีฟัง" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
    { key: "โหมดพิเศษ", value: "Ambient Sound Mode" },
  ],
  "sony-mdr-ex255ap": [
    { key: "ประเภทหูฟัง", value: "In-Ear มีสาย" },
    { key: "ไดรเวอร์", value: "12mm Neodymium" },
    { key: "ตอบสนองความถี่", value: "5Hz – 23,000Hz" },
    { key: "ความไวเสียง", value: "103 dB/mW" },
    { key: "อิมพีแดนซ์", value: "16 โอห์ม" },
    { key: "สายเคเบิล", value: "1.2 เมตร, Y-type" },
    { key: "ไมค์", value: "มีไมค์ + ปุ่มควบคุม Volume" },
    { key: "แจ็ค", value: "3.5mm L-shaped" },
    { key: "น้ำหนัก", value: "4 กรัม" },
  ],
  "sony-mdr-ex15ap": [
    { key: "ประเภทหูฟัง", value: "In-Ear มีสาย" },
    { key: "ไดรเวอร์", value: "9mm" },
    { key: "ตอบสนองความถี่", value: "20Hz – 20,000Hz" },
    { key: "ความไวเสียง", value: "100 dB/mW" },
    { key: "สายเคเบิล", value: "1.2 เมตร" },
    { key: "ไมค์", value: "มีไมค์ + ปุ่มรับสาย" },
    { key: "แจ็ค", value: "3.5mm Stereo" },
    { key: "จุกหู", value: "S / M / L ให้เลือก" },
  ],
  "sony-mdr-ex155ap": [
    { key: "ประเภทหูฟัง", value: "In-Ear มีสาย (Angled)" },
    { key: "ไดรเวอร์", value: "9mm Neodymium" },
    { key: "ตอบสนองความถี่", value: "5Hz – 24,000Hz" },
    { key: "ความไวเสียง", value: "100 dB/mW" },
    { key: "สายเคเบิล", value: "1.2 เมตร, Y-type" },
    { key: "ไมค์", value: "มีไมค์ + ปุ่มรับสาย" },
    { key: "แจ็ค", value: "3.5mm Gold-plated" },
    { key: "น้ำหนัก", value: "3 กรัม" },
  ],
  "sony-wf-ls910n-linkbuds-fit": [
    { key: "ประเภทหูฟัง", value: "True Wireless (TWS) — LinkBuds Fit" },
    { key: "ไดรเวอร์", value: "8.4mm Dynamic" },
    { key: "ระบบตัดเสียง", value: "ANC + Ambient Sound" },
    { key: "Bluetooth", value: "5.3 / รองรับ LDAC, AAC, SBC" },
    { key: "แบตเตอรี่", value: "9 ชม. + 18 ชม. (กล่อง) = 27 ชม. รวม" },
    { key: "กันน้ำ", value: "IPX4" },
    { key: "น้ำหนัก", value: "5.9 กรัม ต่อข้าง" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
    { key: "จับคู่", value: "Google Fast Pair / Swift Pair" },
  ],
  "sony-wf-lc900-linkbuds-clip": [
    { key: "ประเภทหูฟัง", value: "Open-Ear Clip TWS — LinkBuds Clip" },
    { key: "Bluetooth", value: "5.3 / SBC, AAC" },
    { key: "แบตเตอรี่", value: "11 ชม. + 33 ชม. (กล่อง) = 44 ชม. รวม" },
    { key: "กันน้ำ", value: "IPX4" },
    { key: "น้ำหนัก", value: "8.5 กรัม ต่อข้าง" },
    { key: "การออกแบบ", value: "Clip-On ไม่ต้องสอดเข้ารูหู" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
  ],
  "sony-wf-1000xm6": [
    { key: "ประเภทหูฟัง", value: "True Wireless (TWS) — Flagship" },
    { key: "ไดรเวอร์", value: "8.4mm Dynamic Driver X" },
    { key: "ตอบสนองความถี่", value: "4Hz – 40,000Hz (Hi-Res Audio)" },
    { key: "ระบบตัดเสียง", value: "AI Noise Cancelling — Chip QN3" },
    { key: "Bluetooth", value: "5.3 / รองรับ LDAC, AAC, SBC" },
    { key: "แบตเตอรี่", value: "12 ชม. + 24 ชม. (กล่อง) = 36 ชม. รวม" },
    { key: "ชาร์จเร็ว", value: "3 นาที = 60 นาทีฟัง" },
    { key: "กันน้ำ", value: "IPX4" },
    { key: "ไมค์", value: "Bone Conduction + 5 Microphones" },
    { key: "น้ำหนัก", value: "5.9 กรัม ต่อข้าง" },
    { key: "พอร์ตชาร์จ", value: "USB-C (กล่อง) / Wireless Charging" },
  ],
  "sony-wf-l910-linkbuds": [
    { key: "ประเภทหูฟัง", value: "Open TWS (ช่องวงแหวน)" },
    { key: "ไดรเวอร์", value: "12mm Ring Drive" },
    { key: "Bluetooth", value: "5.3 / SBC, AAC, LDAC" },
    { key: "แบตเตอรี่", value: "5.5 ชม. + 12 ชม. (กล่อง) = 17.5 ชม." },
    { key: "กันน้ำ", value: "IPX4" },
    { key: "น้ำหนัก", value: "4.1 กรัม ต่อข้าง" },
    { key: "การออกแบบ", value: "Open Ring Driver — ได้ยินเสียงรอบข้างได้" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
  ],
  "sony-inzone-buds": [
    { key: "ประเภทหูฟัง", value: "True Wireless Gaming TWS" },
    { key: "ไดรเวอร์", value: "Dynamic Driver X (8.4mm)" },
    { key: "ระบบตัดเสียง", value: "ANC (Gaming Optimized)" },
    { key: "Bluetooth", value: "LE Audio + 2.4GHz USB Dongle" },
    { key: "ความหน่วงเสียง", value: "< 30ms (Low Latency mode ผ่าน Dongle)" },
    { key: "แบตเตอรี่", value: "12 ชม. (ตัวหูฟัง) + รวมกล่อง 24 ชม." },
    { key: "กันน้ำ", value: "IPX4" },
    { key: "น้ำหนัก", value: "5.3 กรัม ต่อข้าง" },
    { key: "Platform", value: "PC, PS5, Mobile" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
  ],
  "sony-srs-nb10-neckband": [
    { key: "ประเภท", value: "Wireless Neckband Speaker" },
    { key: "ลำโพง", value: "2 ชุด (ซ้าย-ขวา สวมบ่า)" },
    { key: "Bluetooth", value: "5.0" },
    { key: "แบตเตอรี่", value: "20 ชั่วโมง" },
    { key: "ไมค์", value: "Narrow Directionality (ตัดเสียงรอบข้าง)" },
    { key: "กันน้ำ", value: "IPX4" },
    { key: "น้ำหนัก", value: "113 กรัม" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
    { key: "การใช้งาน", value: "Work From Home, Video Call" },
  ],
  "sony-inzone-mse-g500": [
    { key: "ประเภท", value: "Wireless Gaming Mouse" },
    { key: "Sensor", value: "Custom Optical Sensor (ความแม่นสูง)" },
    { key: "DPI", value: "ปรับได้ 100 – 16,000 DPI" },
    { key: "ปุ่ม", value: "5 ปุ่ม Programmable" },
    { key: "การเชื่อมต่อ", value: "2.4GHz USB Dongle + Bluetooth 5.1" },
    { key: "แบตเตอรี่", value: "ประมาณ 100 ชม. (Bluetooth) / 80 ชม. (2.4GHz)" },
    { key: "น้ำหนัก", value: "70 กรัม (ไม่รวมสาย)" },
    { key: "Platform", value: "PC, PS5" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
  ],
  "sony-inzone-kbd-h75": [
    { key: "ประเภท", value: "Wireless Mechanical Gaming Keyboard" },
    { key: "Switch", value: "Mechanical Tactile (Quiet Click)" },
    { key: "Layout", value: "TKL (Tenkeyless) — English" },
    { key: "การเชื่อมต่อ", value: "2.4GHz USB Dongle + Bluetooth 5.1 + USB-C Wired" },
    { key: "แบตเตอรี่", value: "ประมาณ 2,000 ชม. (Bluetooth, No RGB)" },
    { key: "RGB", value: "Per-Key RGB Backlight" },
    { key: "สาย", value: "Detachable USB-C" },
    { key: "Platform", value: "PC, PS5" },
  ],

  // ════════════════════════════════════════
  // SOUNDCORE HEADPHONES
  // ════════════════════════════════════════
  "soundcore-life-q20-plus": [
    { key: "ประเภทหูฟัง", value: "Over-Ear (Closed-Back)" },
    { key: "ไดรเวอร์", value: "40mm Hi-Res Audio Driver" },
    { key: "ระบบตัดเสียง", value: "Hybrid ANC (ภายใน + ภายนอก)" },
    { key: "Bluetooth", value: "5.0 / SBC, AAC" },
    { key: "แบตเตอรี่", value: "60 ชม. (ANC OFF) / 40 ชม. (ANC ON)" },
    { key: "ปรับ EQ", value: "ผ่านแอป Soundcore (22 Preset)" },
    { key: "น้ำหนัก", value: "265 กรัม" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
    { key: "ไมค์", value: "4 ไมโครโฟน" },
  ],
  "soundcore-q20i": [
    { key: "ประเภทหูฟัง", value: "Over-Ear (Closed-Back)" },
    { key: "ไดรเวอร์", value: "40mm Hi-Res Audio Driver" },
    { key: "ระบบตัดเสียง", value: "Hybrid ANC Multi-Mode (3 ระดับ)" },
    { key: "Bluetooth", value: "5.0 / AAC, SBC" },
    { key: "แบตเตอรี่", value: "40 ชม. (ANC ON) / 60 ชม. (ANC OFF)" },
    { key: "น้ำหนัก", value: "260 กรัม" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
    { key: "โหมดพิเศษ", value: "Transparency Mode" },
  ],

  // ════════════════════════════════════════
  // SOUNDCORE EARBUDS
  // ════════════════════════════════════════
  "soundcore-liberty-4": [
    { key: "ประเภทหูฟัง", value: "True Wireless (TWS)" },
    { key: "ไดรเวอร์", value: "ACAA 3.0 Coaxial Dual Driver (Flagship)" },
    { key: "ระบบตัดเสียง", value: "ANC + Adaptive Transparency" },
    { key: "Bluetooth", value: "5.3 / LDAC, AAC, SBC" },
    { key: "แบตเตอรี่", value: "9 ชม. + 21 ชม. (กล่อง) = 30 ชม. รวม" },
    { key: "เซ็นเซอร์พิเศษ", value: "Heart Rate Sensor (วัดชีพจร)" },
    { key: "ฟีเจอร์พิเศษ", value: "Spatial Audio + Head Tracking" },
    { key: "กันน้ำ", value: "IPX4" },
    { key: "พอร์ตชาร์จ", value: "USB-C + Wireless Charging" },
    { key: "ไมค์", value: "6 ไมโครโฟน AI" },
  ],
  "soundcore-liberty-4-nc": [
    { key: "ประเภทหูฟัง", value: "True Wireless (TWS)" },
    { key: "ไดรเวอร์", value: "11mm Dynamic + 5.8mm BA Dual Driver" },
    { key: "ระบบตัดเสียง", value: "ANC (ตัดเสียง 98.5%)" },
    { key: "Bluetooth", value: "5.3 / LDAC, AAC, SBC" },
    { key: "แบตเตอรี่", value: "10 ชม. + 40 ชม. (กล่อง) = 50 ชม. รวม" },
    { key: "ไมค์", value: "6 ไมโครโฟน AI" },
    { key: "กันน้ำ", value: "IPX4" },
    { key: "พอร์ตชาร์จ", value: "USB-C + Wireless Charging" },
    { key: "ปรับ EQ", value: "ผ่านแอป Soundcore" },
  ],
  "soundcore-life-p3": [
    { key: "ประเภทหูฟัง", value: "True Wireless (TWS)" },
    { key: "ไดรเวอร์", value: "11mm Dynamic" },
    { key: "ระบบตัดเสียง", value: "Hybrid ANC (สูงสุด 35dB)" },
    { key: "Bluetooth", value: "5.0 / AAC, SBC" },
    { key: "แบตเตอรี่", value: "7 ชม. + 28 ชม. (กล่อง) = 35 ชม. รวม" },
    { key: "ไมค์", value: "6 ไมโครโฟน AI" },
    { key: "กันน้ำ", value: "IPX5" },
    { key: "โหมดพิเศษ", value: "Game Mode (Low Latency)" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
  ],
  "soundcore-life-note-3i": [
    { key: "ประเภทหูฟัง", value: "True Wireless (TWS)" },
    { key: "ไดรเวอร์", value: "10mm Dynamic" },
    { key: "ระบบตัดเสียง", value: "Hybrid ANC" },
    { key: "Bluetooth", value: "5.2 / AAC, SBC" },
    { key: "แบตเตอรี่", value: "6 ชม. + 30 ชม. (กล่อง) = 36 ชม. รวม" },
    { key: "ไมค์", value: "4 ไมโครโฟน AI" },
    { key: "กันน้ำ", value: "IPX5" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
  ],
  "soundcore-liberty-air-2-pro-marvel": [
    { key: "ประเภทหูฟัง", value: "True Wireless (TWS) — Marvel Edition" },
    { key: "ไดรเวอร์", value: "Coaxial Dynamic + Hi-Res Audio" },
    { key: "ระบบตัดเสียง", value: "ANC Adaptive (ปรับอัตโนมัติ)" },
    { key: "Bluetooth", value: "5.0 / AAC, SBC" },
    { key: "แบตเตอรี่", value: "7 ชม. + 26 ชม. (กล่อง) = 33 ชม. รวม" },
    { key: "ไมค์", value: "6 ไมโครโฟน AI" },
    { key: "การออกแบบ", value: "Ear Tip ช่องผ่าน (ได้ยินรอบข้างได้)" },
    { key: "พอร์ตชาร์จ", value: "USB-C + Wireless Charging" },
    { key: "Edition", value: "Marvel Limited Edition (ลาย Avengers)" },
  ],
  "soundcore-p40i": [
    { key: "ประเภทหูฟัง", value: "True Wireless (TWS)" },
    { key: "ไดรเวอร์", value: "11mm Bio-Composite Dynamic" },
    { key: "ระบบตัดเสียง", value: "Noise Cancelling 40dB" },
    { key: "Bluetooth", value: "5.3 / AAC, SBC" },
    { key: "แบตเตอรี่", value: "10 ชม. + 40 ชม. (กล่อง) = 50 ชม. รวม" },
    { key: "กันน้ำ", value: "IPX5" },
    { key: "ไมค์", value: "4 ไมโครโฟน AI" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
    { key: "ปรับ EQ", value: "ผ่านแอป Soundcore" },
  ],
  "soundcore-a20i": [
    { key: "ประเภทหูฟัง", value: "True Wireless (TWS) — Entry" },
    { key: "ไดรเวอร์", value: "10mm Dynamic + BassUp" },
    { key: "Bluetooth", value: "5.3 / SBC" },
    { key: "แบตเตอรี่", value: "6 ชม. + 24 ชม. (กล่อง) = 30 ชม. รวม" },
    { key: "กันน้ำ", value: "IPX5" },
    { key: "ไมค์", value: "มีไมค์ในตัว" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
  ],
  "soundcore-space-a40": [
    { key: "ประเภทหูฟัง", value: "True Wireless (TWS)" },
    { key: "ไดรเวอร์", value: "11mm Dynamic" },
    { key: "ระบบตัดเสียง", value: "ANC (ตัดเสียง 98%)" },
    { key: "Bluetooth", value: "5.2 / LDAC, AAC, SBC" },
    { key: "แบตเตอรี่", value: "10 ชม. + 40 ชม. (กล่อง) = 50 ชม. รวม" },
    { key: "ชาร์จกล่อง", value: "Wireless Charging (Qi)" },
    { key: "กันน้ำ", value: "IPX4" },
    { key: "ไมค์", value: "4 ไมโครโฟน AI" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
    { key: "ปรับ EQ", value: "ผ่านแอป Soundcore" },
  ],
  "soundcore-c30i": [
    { key: "ประเภทหูฟัง", value: "Open-Ear Clip TWS" },
    { key: "Bluetooth", value: "5.3 / AAC, SBC" },
    { key: "แบตเตอรี่", value: "8 ชม. + 22 ชม. (กล่อง) = 30 ชม. รวม" },
    { key: "การออกแบบ", value: "Clip-Ear (หนีบใบหู ไม่ต้องยัด)" },
    { key: "การเชื่อมต่อ", value: "Multipoint 2 อุปกรณ์" },
    { key: "ไมค์", value: "มีไมค์ AI" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
  ],
  "soundcore-aerofit-pro": [
    { key: "ประเภทหูฟัง", value: "Open-Ear Sport TWS" },
    { key: "ไดรเวอร์", value: "16.2mm Dynamic" },
    { key: "Bluetooth", value: "5.3 / AAC, SBC" },
    { key: "แบตเตอรี่", value: "9 ชม. + 27 ชม. (กล่อง) = 36 ชม. รวม" },
    { key: "กันน้ำ", value: "IPX7" },
    { key: "การออกแบบ", value: "Spatial Directional Driver — ไม่ยัดรูหู" },
    { key: "สายพิเศษ", value: "แม่เหล็กถอดได้ ป้องกันหล่น" },
    { key: "น้ำหนัก", value: "9.3 กรัม ต่อข้าง" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
  ],
  "soundcore-sport-x10": [
    { key: "ประเภทหูฟัง", value: "True Wireless Sport TWS" },
    { key: "ไดรเวอร์", value: "12mm Dynamic" },
    { key: "Bluetooth", value: "5.2 / AAC, SBC" },
    { key: "แบตเตอรี่", value: "8 ชม. + 32 ชม. (กล่อง) = 40 ชม. รวม" },
    { key: "กันน้ำ", value: "IPX7 (จุ่มน้ำ 1m x 30 นาที)" },
    { key: "Ear Hook", value: "Rotating Silicon Wing (ปรับมุมได้)" },
    { key: "น้ำหนัก", value: "12 กรัม ต่อข้าง" },
    { key: "ไมค์", value: "4 ไมโครโฟน AI" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
  ],

  // Soundcore Speakers
  "soundcore-motion-boom": [
    { key: "ประเภท", value: "Portable Outdoor Bluetooth Speaker" },
    { key: "กำลังขับ", value: "30W (Titanium Driver คู่)" },
    { key: "ตอบสนองความถี่", value: "50Hz – 20,000Hz" },
    { key: "Bluetooth", value: "5.0" },
    { key: "แบตเตอรี่", value: "24 ชั่วโมง" },
    { key: "กันน้ำ", value: "IPX7" },
    { key: "ฟีเจอร์พิเศษ", value: "BassUp, PartyCast" },
    { key: "น้ำหนัก", value: "940 กรัม" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
  ],
  "soundcore-boom-2-se": [
    { key: "ประเภท", value: "Portable Outdoor Bluetooth Speaker" },
    { key: "กำลังขับ", value: "30W (Titanium Driver คู่)" },
    { key: "Bluetooth", value: "5.3" },
    { key: "แบตเตอรี่", value: "24 ชั่วโมง" },
    { key: "กันน้ำ", value: "IPX7" },
    { key: "ฟีเจอร์พิเศษ", value: "BassUp 2.0, PartyCast 2.0, PowerBank" },
    { key: "น้ำหนัก", value: "980 กรัม" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
    { key: "ชาร์จมือถือ", value: "PowerBank USB-A Out" },
  ],
  "soundcore-mini-3": [
    { key: "ประเภท", value: "Portable Compact Bluetooth Speaker" },
    { key: "กำลังขับ", value: "6W" },
    { key: "เสียง", value: "360° Sound" },
    { key: "Bluetooth", value: "5.0" },
    { key: "แบตเตอรี่", value: "15 ชั่วโมง" },
    { key: "กันน้ำ", value: "IPX7" },
    { key: "ฟีเจอร์พิเศษ", value: "BassUp, PartyCast" },
    { key: "น้ำหนัก", value: "250 กรัม" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
  ],
  "soundcore-mini-3-pro": [
    { key: "ประเภท", value: "Portable Compact Bluetooth Speaker + LED" },
    { key: "กำลังขับ", value: "6W" },
    { key: "เสียง", value: "360° Sound" },
    { key: "ไฟ LED", value: "Ambient Light (รอบตัวลำโพง)" },
    { key: "Bluetooth", value: "5.0" },
    { key: "แบตเตอรี่", value: "12 ชม. (LED ON) / 15 ชม. (LED OFF)" },
    { key: "กันน้ำ", value: "IPX7" },
    { key: "ฟีเจอร์พิเศษ", value: "BassUp, PartyCast" },
    { key: "น้ำหนัก", value: "260 กรัม" },
  ],
  "soundcore-flare-mini": [
    { key: "ประเภท", value: "Portable Party Bluetooth Speaker" },
    { key: "กำลังขับ", value: "10W" },
    { key: "เสียง", value: "360° Sound" },
    { key: "ไฟ LED", value: "Party Mode LED รอบฐาน" },
    { key: "Bluetooth", value: "5.0" },
    { key: "แบตเตอรี่", value: "12 ชั่วโมง" },
    { key: "กันน้ำ", value: "IPX7" },
    { key: "ฟีเจอร์พิเศษ", value: "BassUp, PartyCast" },
    { key: "น้ำหนัก", value: "490 กรัม" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
  ],
  "soundcore-flare-2": [
    { key: "ประเภท", value: "Portable Party Bluetooth Speaker" },
    { key: "กำลังขับ", value: "20W" },
    { key: "เสียง", value: "360° Sound" },
    { key: "ไฟ LED", value: "Party LED สลับสีตามจังหวะดนตรี" },
    { key: "Bluetooth", value: "5.0" },
    { key: "แบตเตอรี่", value: "12 ชั่วโมง" },
    { key: "กันน้ำ", value: "IPX7" },
    { key: "ฟีเจอร์พิเศษ", value: "BassUp, PartyCast" },
    { key: "น้ำหนัก", value: "680 กรัม" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
  ],

  // ════════════════════════════════════════
  // EDIFIER
  // ════════════════════════════════════════
  "edifier-w80": [
    { key: "ประเภทหูฟัง", value: "Over-Ear (Closed-Back)" },
    { key: "ระบบตัดเสียง", value: "ANC -49dB (Hybrid)" },
    { key: "Bluetooth", value: "5.3 / รองรับ LDAC, aptX Adaptive, AAC" },
    { key: "แบตเตอรี่", value: "60 ชม. (ANC OFF) / 40 ชม. (ANC ON)" },
    { key: "ชาร์จเร็ว", value: "10 นาที = 2 ชั่วโมงฟัง" },
    { key: "ไมค์", value: "6 ไมโครโฟน AI Beamforming" },
    { key: "ปรับ EQ", value: "ผ่านแอป Edifier Connect" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
    { key: "น้ำหนัก", value: "~250 กรัม" },
  ],
  "edifier-neobuds-planar": [
    { key: "ประเภทหูฟัง", value: "True Wireless (TWS) — Planar Magnetic" },
    { key: "ไดรเวอร์", value: "Planar Magnetic Driver (Hi-Res Grade)" },
    { key: "ระบบตัดเสียง", value: "Hybrid ANC" },
    { key: "Bluetooth", value: "5.3 / รองรับ LDAC, AAC, SBC" },
    { key: "แบตเตอรี่", value: "6 ชม. + 24 ชม. (กล่อง) = 30 ชม. รวม" },
    { key: "ไมค์", value: "6 ไมโครโฟน AI" },
    { key: "กันน้ำ", value: "IP54" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
    { key: "ปรับ EQ", value: "ผ่านแอป Edifier Connect" },
  ],
  "edifier-neodots": [
    { key: "ประเภทหูฟัง", value: "True Wireless (TWS) — Hybrid Driver" },
    { key: "ไดรเวอร์", value: "Dynamic Driver + Knowles BA Driver" },
    { key: "ระบบตัดเสียง", value: "ANC (Hybrid)" },
    { key: "Bluetooth", value: "5.4 / รองรับ LDAC, AAC, SBC" },
    { key: "แบตเตอรี่", value: "8 ชม. + 48 ชม. (กล่อง) = 56 ชม. รวม" },
    { key: "ไมค์", value: "6 ไมโครโฟน AI" },
    { key: "กันน้ำ", value: "IP54" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
  ],
  "edifier-stax-spirit-s10": [
    { key: "ประเภทหูฟัง", value: "True Wireless (TWS) — Planar Magnetic Flagship" },
    { key: "ไดรเวอร์", value: "Planar Magnetic Driver (Hi-End)" },
    { key: "ตอบสนองความถี่", value: "20Hz – 40,000Hz (Hi-Res Audio)" },
    { key: "ระบบตัดเสียง", value: "Hybrid ANC Multi-Channel" },
    { key: "Bluetooth", value: "5.4 / รองรับ LDAC, aptX Lossless, AAC" },
    { key: "แบตเตอรี่", value: "8 ชม. + 24 ชม. (กล่อง) = 32 ชม. รวม" },
    { key: "ไมค์", value: "6 ไมโครโฟน AI Noise Cancelling" },
    { key: "กันน้ำ", value: "IP54" },
    { key: "พอร์ตชาร์จ", value: "USB-C + Wireless Charging" },
    { key: "ปรับ EQ", value: "ผ่านแอป Edifier Connect" },
  ],
  "edifier-neobuds-plus": [
    { key: "ประเภทหูฟัง", value: "True Wireless (TWS)" },
    { key: "ไดรเวอร์", value: "Knowles BA Driver" },
    { key: "ระบบตัดเสียง", value: "ANC (Hybrid)" },
    { key: "Bluetooth", value: "5.4 / รองรับ LDAC, AAC, SBC" },
    { key: "แบตเตอรี่", value: "7 ชม. + 28 ชม. (กล่อง) = 35 ชม. รวม" },
    { key: "ไมค์", value: "6 ไมโครโฟน AI" },
    { key: "กันน้ำ", value: "IPX54" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
  ],
  "edifier-neobuds-pro-3": [
    { key: "ประเภทหูฟัง", value: "True Wireless (TWS)" },
    { key: "ไดรเวอร์", value: "Knowles BA + Dynamic Hybrid" },
    { key: "ระบบตัดเสียง", value: "Multi-Channel ANC" },
    { key: "Bluetooth", value: "5.4 / รองรับ LDAC, AAC" },
    { key: "แบตเตอรี่", value: "9 ชม. + 27 ชม. (กล่อง) = 36 ชม. รวม" },
    { key: "ไมค์", value: "8 ไมโครโฟน AI" },
    { key: "กันน้ำ", value: "IP54" },
    { key: "พอร์ตชาร์จ", value: "USB-C + Wireless Charging" },
    { key: "ปรับ EQ", value: "ผ่านแอป Edifier Connect" },
  ],
  "edifier-evobuds": [
    { key: "ประเภทหูฟัง", value: "True Wireless (TWS)" },
    { key: "ระบบตัดเสียง", value: "Adaptive ANC 38dB" },
    { key: "Bluetooth", value: "6.1 (รุ่นใหม่ล่าสุด) / AAC, SBC" },
    { key: "แบตเตอรี่", value: "7 ชม. + 28 ชม. (กล่อง) = 35 ชม. รวม" },
    { key: "ไมค์", value: "4 ไมโครโฟน AI" },
    { key: "กันน้ำ", value: "IP54" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
    { key: "จุดเด่น", value: "Bluetooth 6.1 ล่าสุด ประหยัดพลังงานสูง" },
  ],
  "edifier-lolliclip": [
    { key: "ประเภทหูฟัง", value: "Open-Ear Clip TWS" },
    { key: "ระบบตัดเสียง", value: "ANC (หายากสำหรับ Open-Ear)" },
    { key: "Bluetooth", value: "5.4 / AAC, SBC" },
    { key: "แบตเตอรี่", value: "8 ชม. + 22 ชม. (กล่อง) = 30 ชม. รวม" },
    { key: "ไมค์", value: "6 ไมโครโฟน AI" },
    { key: "การเชื่อมต่อ", value: "Multipoint 2 อุปกรณ์" },
    { key: "การออกแบบ", value: "Clip-On ใบหู ไม่ต้องสอดหู" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
  ],
  "edifier-comfo-q": [
    { key: "ประเภทหูฟัง", value: "Open-Ear Sport TWS" },
    { key: "Bluetooth", value: "5.4 / AAC, SBC" },
    { key: "แบตเตอรี่", value: "8 ชม. + 32 ชม. (กล่อง) = 40 ชม. รวม" },
    { key: "ไมค์", value: "AI Microphone" },
    { key: "การเชื่อมต่อ", value: "Multipoint 2 อุปกรณ์" },
    { key: "การออกแบบ", value: "Open-Ear เน้นความสบาย" },
    { key: "พอร์ตชาร์จ", value: "USB-C" },
  ],
};

async function run() {
  console.log("🔩 Starting Specs Import for all products...\n");

  let successCount = 0;
  let notFoundCount = 0;

  for (const [slug, specs] of Object.entries(specsDB)) {
    // Find the product by slug
    const { data: product, error: fetchError } = await supabase
      .from('products')
      .select('id, name')
      .eq('slug', slug)
      .single();

    if (fetchError || !product) {
      console.log(`⚠️  Product not found: ${slug}`);
      notFoundCount++;
      continue;
    }

    // Delete existing specs first (to avoid duplicates)
    await supabase.from('specs').delete().eq('product_id', product.id);

    // Insert new specs
    const { error: insertError } = await supabase.from('specs').insert(
      specs.map(s => ({ product_id: product.id, key: s.key, value: s.value }))
    );

    if (insertError) {
      console.error(`❌ Error for ${product.name}: ${insertError.message}`);
    } else {
      console.log(`✅ ${product.name} — ${specs.length} specs inserted`);
      successCount++;
    }
  }

  console.log(`\n🎉 Specs import complete! ✅ ${successCount} products updated | ⚠️ ${notFoundCount} not found`);
}

run();
